language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - quizzer-app/node_modules
script:
  - npm test
  - npm run install-ui
  - npm run build-ui
deploy:
  provider: heroku
  api_key:
    secure: ""